### ISSUE TITLE
Galleries mock-up and page content

### ISSUE THREAD

**Issue by CaleumSeanFoxNorbury** [CaleumSeanFoxNorbury/ArtBank#16]
Galleries will be displaying galleries or (art collections) within the gallery page of the application, this will be set up to display blocks of front cover gallery images which will be seperated by categories and filters. See projects data-modelling for object specs. 

**Tasks:**

- [ ] Apply `Galleries` object 
- [ ] Apply `GalleriesCategory` object 
- [ ] Document Gallery and assoicated objects 
- [ ] Implement galleries page displaying block image links to each gallery
- [ ] Seperate galleries in gallery page by `GalleryCategory`
- [ ] Apply `GalleryCatgeories` and `Gallery` on `ContentBanner` in explore
